"""Shared fixtures for the toolbox tests. No network is touched by any of them."""

from __future__ import annotations

from pathlib import Path

import pytest

#: Recorded GitHub responses, regenerated by backend/tests/fixtures/build_github_cache.py
CACHE_FIXTURE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "github_cache"
FIXTURE_REPO = "acme/widgets"
EVALUATED_ISSUE = 202


@pytest.fixture
def github_env(monkeypatch: pytest.MonkeyPatch):
    """Point the GitHub tools at the recorded cache with no token and no live mode."""
    monkeypatch.setenv("GITHUB_REPO", FIXTURE_REPO)
    monkeypatch.setenv("GITHUB_CACHE_DIR", str(CACHE_FIXTURE_DIR))
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)
    monkeypatch.delenv("GITHUB_LIVE", raising=False)
    monkeypatch.setenv("GITHUB_RETRY_BASE_SECONDS", "0")

    from backend.toolbox import github

    def _no_network(*args, **kwargs):  # pragma: no cover - only fires on a bug
        raise AssertionError("a toolbox test tried to reach the network")

    monkeypatch.setattr(github.urllib.request, "urlopen", _no_network)
    return github


@pytest.fixture
def under_evaluation(github_env):
    """Set the evaluator case so issue 202's ground truth must be redacted."""
    github = github_env
    var = github._case_var()
    token = var.set(
        {
            "id": "case-202",
            "split": "train",
            "input": {"issue_number": EVALUATED_ISSUE},
            "expected": {"labels": ["bug"], "component": "terminal"},
        }
    )
    yield github
    var.reset(token)
