"""The toolbox registry: name -> tool module, plus materialisation into an agent package.

``TOOLBOX`` maps a tool name to the module that implements it. Every module
exposes ``TOOL`` (an LLM-ready ``{name, description, input_schema}``) and
``run(input: dict) -> str``.

``write_agent_tool(name, dest_dir)`` writes ``<dest_dir>/<name>.py`` into an
agent package. ``TOOL`` is written as a literal dict -- a **copy**, not a
reference -- so W6's ``tools`` lever can edit a tool's description, defaults
or messages in the package copy without touching the shared toolbox (§K);
``run`` is still imported from the toolbox, so the implementation is not
duplicated and a bug fix there reaches every agent at once. It also means
reading a package's tool specs is a structural parse (``ast.literal_eval`` on
the ``TOOL = {...}`` assignment) rather than an import -- see
``backend.architect``'s package inspector, which must not execute
arbitrary (possibly LLM-authored glue-tool) code just to list tool names.
"""

from __future__ import annotations

import pprint
from pathlib import Path
from types import ModuleType

from . import date_parse, html_to_text, json_validate, number_parse, regex_extract
from .github_tools import (
    component_owners,
    issue_context,
    label_taxonomy,
    similar_issues,
)

_MODULES: tuple[ModuleType, ...] = (
    html_to_text,
    regex_extract,
    date_parse,
    json_validate,
    number_parse,
    issue_context,
    similar_issues,
    label_taxonomy,
    component_owners,
)

#: name -> module. The single source of truth for what tools exist.
TOOLBOX: dict[str, ModuleType] = {module.TOOL["name"]: module for module in _MODULES}

#: Tools that reach a third-party API (everything else is pure and offline).
GITHUB_TOOLS: tuple[str, ...] = tuple(
    name for name, module in TOOLBOX.items() if ".github_tools." in module.__name__
)

#: Tools with no network access at all.
OFFLINE_TOOLS: tuple[str, ...] = tuple(name for name in TOOLBOX if name not in GITHUB_TOOLS)


class UnknownToolError(KeyError):
    """Raised when a tool name is not in the toolbox."""


def get(name: str) -> ModuleType:
    """The module implementing ``name``, or ``UnknownToolError`` listing what exists."""
    try:
        return TOOLBOX[name]
    except KeyError:
        raise UnknownToolError(
            f"unknown tool {name!r}; the toolbox contains: {', '.join(sorted(TOOLBOX))}"
        ) from None


def spec(name: str) -> dict:
    """The ``{name, description, input_schema}`` definition for one tool."""
    return get(name).TOOL


def specs(names: list[str] | tuple[str, ...] | None = None) -> list[dict]:
    """Tool definitions, ready to pass to ``llm.complete(..., tools=...)``."""
    selected = sorted(TOOLBOX) if names is None else list(names)
    return [spec(name) for name in selected]


def run(name: str, input: dict) -> str:
    """Execute a tool by name. Unknown names come back as an error string, not an exception."""
    try:
        module = get(name)
    except UnknownToolError as exc:
        return f"ERROR: {exc}"
    return module.run(input)


def unknown(names: list[str] | tuple[str, ...]) -> list[str]:
    """Which of ``names`` are not in the toolbox."""
    return [name for name in names if name not in TOOLBOX]


_TEMPLATE = '''"""Tool {name}.

Generated by toolbox.registry.write_agent_tool from {module}. TOOL below is a
literal copy the improver may edit in place (the `tools` lever, section K) --
it is read by parsing, never by importing, so an edit here is safe even before
`run` is touched. `run` is imported from the toolbox; editing TOOL alone
changes what the model is told, not what the tool actually does.
"""

from {module} import run

TOOL = {tool_literal}

__all__ = ["TOOL", "run"]
'''


def write_agent_tool(name: str, dest_dir: str | Path) -> Path:
    """Write ``<dest_dir>/<name>.py`` with a literal ``TOOL`` and an imported ``run``."""
    module = get(name)
    destination = Path(dest_dir)
    destination.mkdir(parents=True, exist_ok=True)
    path = destination / f"{name}.py"
    tool_literal = pprint.pformat(module.TOOL, width=88, sort_dicts=False)
    path.write_text(
        _TEMPLATE.format(name=name, module=module.__name__, tool_literal=tool_literal),
        encoding="utf-8",
    )
    return path


def write_agent_tools(names: list[str] | tuple[str, ...], dest_dir: str | Path) -> list[Path]:
    """Materialise several tools into an agent package's ``tools/`` directory."""
    return [write_agent_tool(name, dest_dir) for name in names]
