"""The toolbox registry: name -> tool module, plus materialisation into an agent package.

``TOOLBOX`` maps a tool name to the module that implements it. Every module
exposes ``TOOL`` (an LLM-ready ``{name, description, input_schema}``) and
``run(input: dict) -> str``.

``write_agent_tool(name, dest_dir)`` writes ``<dest_dir>/<name>.py`` into an
agent package. The generated file re-exports ``TOOL`` and ``run`` from the
toolbox rather than copying the implementation, so an agent package stays a
small, self-contained, importable directory that satisfies
``contracts.agent.validate_package`` while bug fixes to a shared tool reach
every agent at once.
"""

from __future__ import annotations

from pathlib import Path
from types import ModuleType

from . import date_parse, html_to_text, json_validate, number_parse, regex_extract
from .github_tools import (
    component_owners,
    issue_context,
    label_taxonomy,
    similar_issues,
)

_MODULES: tuple[ModuleType, ...] = (
    html_to_text,
    regex_extract,
    date_parse,
    json_validate,
    number_parse,
    issue_context,
    similar_issues,
    label_taxonomy,
    component_owners,
)

#: name -> module. The single source of truth for what tools exist.
TOOLBOX: dict[str, ModuleType] = {module.TOOL["name"]: module for module in _MODULES}

#: Tools that reach a third-party API (everything else is pure and offline).
GITHUB_TOOLS: tuple[str, ...] = tuple(
    name for name, module in TOOLBOX.items() if ".github_tools." in module.__name__
)

#: Tools with no network access at all.
OFFLINE_TOOLS: tuple[str, ...] = tuple(name for name in TOOLBOX if name not in GITHUB_TOOLS)


class UnknownToolError(KeyError):
    """Raised when a tool name is not in the toolbox."""


def get(name: str) -> ModuleType:
    """The module implementing ``name``, or ``UnknownToolError`` listing what exists."""
    try:
        return TOOLBOX[name]
    except KeyError:
        raise UnknownToolError(
            f"unknown tool {name!r}; the toolbox contains: {', '.join(sorted(TOOLBOX))}"
        ) from None


def spec(name: str) -> dict:
    """The ``{name, description, input_schema}`` definition for one tool."""
    return get(name).TOOL


def specs(names: list[str] | tuple[str, ...] | None = None) -> list[dict]:
    """Tool definitions, ready to pass to ``llm.complete(..., tools=...)``."""
    selected = sorted(TOOLBOX) if names is None else list(names)
    return [spec(name) for name in selected]


def run(name: str, input: dict) -> str:
    """Execute a tool by name. Unknown names come back as an error string, not an exception."""
    try:
        module = get(name)
    except UnknownToolError as exc:
        return f"ERROR: {exc}"
    return module.run(input)


def unknown(names: list[str] | tuple[str, ...]) -> list[str]:
    """Which of ``names`` are not in the toolbox."""
    return [name for name in names if name not in TOOLBOX]


_TEMPLATE = '''"""Tool {name}, re-exported from the shared toolbox.

Generated by toolbox.registry.write_agent_tool. Do not edit by hand -- edit
{module} instead. The agent package keeps this file so it is self-describing
and validates against contracts/agent.py.
"""

from {module} import TOOL, run

__all__ = ["TOOL", "run"]
'''


def write_agent_tool(name: str, dest_dir: str | Path) -> Path:
    """Write ``<dest_dir>/<name>.py`` re-exporting ``TOOL`` and ``run``. Returns the path."""
    module = get(name)
    destination = Path(dest_dir)
    destination.mkdir(parents=True, exist_ok=True)
    path = destination / f"{name}.py"
    path.write_text(_TEMPLATE.format(name=name, module=module.__name__), encoding="utf-8")
    return path


def write_agent_tools(names: list[str] | tuple[str, ...], dest_dir: str | Path) -> list[Path]:
    """Materialise several tools into an agent package's ``tools/`` directory."""
    return [write_agent_tool(name, dest_dir) for name in names]
