"""Valid payloads for every event kind, shared by the contract and ledger tests."""

from __future__ import annotations

__all__ = ["VALID_PAYLOADS"]

VALID_PAYLOADS: dict[str, dict] = {
    "agent_created": {
        "goal": "triage GitHub issues",
        "domain": "github_triage",
        "tools": ["list_issues", "get_issue"],
        "evaluator_id": "github_triage",
        "orchestration": "single",
        "applied_lessons": [],
    },
    "run_started": {"split": "train", "case_count": 42, "repeats": 3},
    "case_result": {
        "case_id": "issue_412",
        "repeat": 0,
        "passed": False,
        "score": 0.5,
        "tokens_in": 1200,
        "tokens_out": 180,
        "cost_usd": 0.0042,
        "latency_ms": 3100,
        "steps": 4,
        "transcript_path": "runs/r_1/issue_412.r0.json",
        "tool_calls": 3,
        "tool_errors": 1,
        "rules_injected": ["rule_1a2b3c"],
    },
    "drift_detected": {
        "case_id": "issue_412",
        "repeat": 1,
        "step": 7,
        "kind": "loop",
        "evidence": "list_issues({'state': 'open'}) called 3x",
        "action": "nudge",
        "tokens_at_detection": 8200,
    },
    "run_finished": {
        "split": "train",
        "repeats": 3,
        "pass_rate_mean": 0.62,
        "pass_rate_std": 0.04,
        "pass_rate_min": 0.57,
        "pass_rate_max": 0.66,
        "total_cost_usd": 1.24,
        "p50_latency_ms": 2900,
        "p95_latency_ms": 8100,
        "drift_count": 2,
        "tokens_saved_by_drift": 14000,
    },
    "issue_opened": {
        "issue_id": "iss_1",
        "source": "human",
        "title": "Windows reports get the wrong label",
        "failure_signature": "labels:missing:platform-windows",
    },
    "issue_linked_case": {"issue_id": "iss_1", "case_id": "issue_412"},
    "fix_proposed": {
        "issue_id": "iss_1",
        "from_version": 0,
        "to_version": 1,
        "lever": "memory",
        "failing_group": {
            "signature": "labels:missing:platform-windows",
            "tag": "windows",
            "case_ids": ["issue_412", "issue_455"],
            "count": 2,
        },
        "hypothesis": "The agent has no rule mapping ConPTY reports to platform:windows.",
        "diagnosis": "5 of 6 failures in this group omit platform:windows.",
        "diff_path": "runs/fixes/v1.diff",
        "diff_summary": "+2 rules in memory/rules.jsonl",
        "files_touched": ["agents/a1/v1/memory/rules.jsonl"],
    },
    "fix_accepted": {
        "to_version": 1,
        "train_pass_rate_before": {"mean": 0.5, "std": 0.03},
        "train_pass_rate_after": {"mean": 0.62, "std": 0.04},
        "group_pass_before": 0.0,
        "group_pass_after": 0.83,
        "holdout_pass_rate_after": {"mean": 0.58, "std": 0.05},
        "cost_per_run_before": 0.31,
        "cost_per_run_after": 0.27,
    },
    "fix_rejected": {
        "to_version": 2,
        "reason": "regression",
        "regressed_case_ids": ["issue_301"],
        "train_pass_rate_candidate": {"mean": 0.55, "std": 0.06},
    },
    "lesson_recorded": {
        "lesson_id": "lesson_7c1d",
        "lever": "memory",
        "trigger": "free text mapped to a fixed label vocabulary",
        "lesson": "Write one rule per label with the signal that selects it.",
        "source_agent_id": "a1",
    },
    "memory_written": {
        "entry_id": "rule_1a2b3c",
        "kind": "rule",
        "source": "reflection",
        "evidence_case_ids": ["issue_412"],
        "version": 1,
    },
    "memory_demoted": {"entry_id": "rule_9z8y", "hits": 1, "misses": 3, "version": 2},
}
